name: Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  static-analysis:
    name: 'Lint and Type-check'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Build library
        run: pnpm run build

      - name: Type Check
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Generate language definitions
        run: pnpm run build:languages

      - name: Unit Test
        run: pnpm run test
